# Generated by Django 3.2.12 on 2024-07-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('contacted_at', models.DateField(auto_created=True, auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(default='', max_length=50)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_number', models.CharField(default='', max_length=20)),
                ('client_message', models.CharField(default='', max_length=225)),
                ('client_service', models.CharField(choices=[('Mobile App', 'Mobile App'), ('Web Development', 'Web Development'), ('ERP Systems', 'ERP Systems'), ('Digital Marketing', 'Digital Marketing'), ('Graphic Design', 'Graphic Design')], default='Web Development', max_length=20)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Done', 'Done'), ('Dealed', 'Dealed'), ('Archived', 'Archived')], default='Waiting', max_length=10)),
            ],
        ),
    ]
