# Generated by Django 3.2.12 on 2024-07-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='client_service',
            field=models.CharField(choices=[('Mobile App', 'Mobile App'), ('Web Development', 'Web Development'), ('ERP Systems', 'ERP Systems'), ('Digital Marketing', 'Digital Marketing'), ('Graphic Design', 'Graphic Design'), ('Multi Service', 'Multi Service')], default='Web Development', max_length=20),
        ),
    ]
