# Generated by Django 3.2.12 on 2024-07-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
    ]
