# Generated by Django 5.0.7 on 2024-07-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(default='', max_length=125)),
                ('client_review', models.CharField(default='', max_length=225)),
                ('client_rate', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
    ]
