# Generated by Django 5.0.7 on 2024-07-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reviews_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='client_image',
            field=models.ImageField(default=1, upload_to='client_image/'),
            preserve_default=False,
        ),
    ]
