# Generated by Django 3.2.12 on 2024-07-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(default='', max_length=125)),
                ('course_description', models.TextField(default='')),
                ('course_image', models.ImageField(upload_to='course_images/')),
                ('course_link', models.URLField(default='', unique=True)),
                ('course_hours', models.IntegerField(default=0)),
                ('course_price', models.FloatField(default=0.0)),
                ('course_price_currency', models.CharField(default='', max_length=3)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
    ]
