# Generated by Django 4.2 on 2024-07-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_category',
            field=models.CharField(default='', max_length=25),
        ),
    ]
