# Generated by Django 4.2 on 2024-07-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_category',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
