# Generated by Django 4.2 on 2024-07-30 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_id', models.IntegerField(default=0, unique=True)),
                ('std_name', models.CharField(default='', max_length=75, unique=True)),
                ('std_email', models.EmailField(max_length=254, unique=True)),
                ('issued_at', models.DateTimeField()),
                ('is_archived', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courses.courses')),
            ],
        ),
    ]
