# Generated by Django 3.2.12 on 2024-07-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('portfolio_service', models.CharField(choices=[('Mobile App', 'Mobile App'), ('Web Development', 'Web Development'), ('ERP Systems', 'ERP Systems'), ('Digital Marketing', 'Digital Marketing'), ('Graphic Design', 'Graphic Design'), ('Multi Service', 'Multi Service')], default='Multi Service', max_length=25)),
                ('portfolio_title', models.CharField(default='', max_length=25)),
                ('portfolio_description', models.CharField(default='', max_length=225)),
                ('portfolio_image', models.ImageField(upload_to='portfolio/')),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
    ]
