# Generated by Django 4.2.11 on 2024-12-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_service',
        ),
    ]
